### ISSUE TITLE
Error parsing inputs file with extra inputs

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#133]
## Current behaviour
The following inputs file for Snow is parsed incorrectly by IDE inputs wizard
```yaml
ssh-key-name: test
docker-registry-cert-email-address: test@test.com
test: _test
env: 
```
![image](https://user-images.githubusercontent.com/24526114/113299427-28927480-92fd-11eb-9731-ef82acb24d3b.png)
## Expected behaviour
Inputs file is parsed correctly
