### ISSUE TITLE
Error parsing inputs file with new lines

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#138]
If an inputs file contains extra new lines (e.g. when we want to separate long inputs for better readability), the inputs values coming after a new line are not populated.

E.g. in AADM:
```yaml
import: openstack

inputs:

  name:  
    type: string 
  network:  
    type: string 
  security_groups:  
    type: string 

node_templates:

  aws-keypair:
    type: openstack/sodalite.nodes.OpenStack.VM
    properties:  
      name: get_input: name
      network: get_input: network
      security_groups: get_input: security_groups
```

With inputs file:
```yaml
name: some-vm
network: some-network

security_groups: some-group
```

The result is:
![Screenshot from 2021-04-12 15-12-39](https://user-images.githubusercontent.com/2138519/114399758-92ced300-9ba1-11eb-8fe5-3684f2c22645.png)

As can be seen, the security_groups is empty.
