### ISSUE TITLE
required properties - required:false in exchange ttl

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/ide#139]
If no required is set in a property, then  IDE adds **required:false** in the exchange ttl.
In TOSCA, if no required is set, it implicitly means that **required:true**

EXAMPLE IN THE CLINICAL UC
**For a property that does not have required in the DSL:** IDE can either set **required:true** or no required in the exchange ttl :

```
node_types:

  sodalite.nodes.batch.Container.Application:
    derived_from: tosca.nodes.Root
    properties:
      app_tag:
        type: string
```
**exchange ttl**

```
:Parameter_118
  rdf:type exchange:Parameter ;
  exchange:name "type" ;
  exchange:value 'string' ;  
.

:Parameter_119
  rdf:type exchange:Parameter ;
  exchange:name "required" ;
  exchange:value 'false' ;
.
:Property_3
  rdf:type exchange:Property ;
  exchange:name "app_tag" ;
  exchange:hasParameter :Parameter_118 ;
  exchange:hasParameter :Parameter_119 ;
.
```

If you can, try to fix it locally, and save the three use cases (possibly new required properties will appear - possibly errors during saving), so as to ensure that the use cases will work in the review.
If we notice issues in the use cases, we can postpone the fix after the review.
