### ISSUE TITLE
IDE Alerting rule DSL and Editor

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [SODALITE-EU/ide#155]
Create a DSL and associated XText textual editor for creating alerting rules. Support content assistance with Prometheus available metrics. Support rule saving into the Files Rule engine

**Comment by jramosrivas** [comment]
Example ruleset file:

```
#This is how the ruleset file should end up looking like.
groups:
- name: alert.rules
  rules:
  - alert: OutOfDiskSpace
    expr: (node_filesystem_avail_bytes{deployment_id="5sdfsdf121-sdf51s2df1-s45d51f121sdf"} * 100) / node_filesystem_size_bytes{deployment_id="5sdfsdf121-sdf51s2df1-s45d51f121sdf"} < 25 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Disk space running low (instance {{ $labels.instance }})
      description: 'Available disk space is low (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
  - alert: CoresHighCPU
    expr: ((count by (instance) ((1-rate(node_cpu_seconds_total{mode="idle",deployment_id="5sdfsdf121-sdf51s2df1-s45d51f121sdf"}[1m]))>0.75))/(count by (instance) (node_cpu_seconds_total{mode="idle",deployment_id="5sdfsdf121-sdf51s2df1-s45d51f121sdf"})) OR on() vector(0) )> 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 'More than 50% of cores are above 75% load (instance {{ $labels.instance }})'
      description: 'Percentage of cores above 75% load is > 50%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'
  - alert: LowReceivedNetworkTraffic
    expr: sum by (instance) (increase(node_network_receive_bytes_total{deployment_id="5sdfsdf121-sdf51s2df1-s45d51f121sdf"}[1h])) < 30000000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 'Low incoming network traffic (instance {{ $labels.instance }})'
      description: 'Received network traffic in the last hour is < 30MB\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}'

```
