### ISSUE TITLE
Add Apache NiFi settings and access token into the deployment inputs 

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/ide#193]
# Desired state
An Apache NiFi cluster is available at `NIFI_ENDPOINT`. IDE should provide an option to set this endpoint and the flag to validate SSL certificates (see `NIFI_API_VALIDATE_CERTS` below) in the backend settings.

IDE should authenticate with the Apache NiFi cluster and inject the following inputs to the deployment:
```
NIFI_ENDPOINT:
  type: string
  description: the endpoint of Apache NiFi that is set in the IDE backend settings
  example: https://nifi01.nifi.cluster:9543
NIFI_API_ENDPOINT:
  type: string
  description: the endpoint to the Apache NiFi API. It equals to NIFI_ENDPOINT/nifi-api
  example: https://nifi01.nifi.cluster:9543/nifi-api
NIFI_API_ACCESS_TOKEN:
  type: string
  description: an access token obtained after the NiFi authentication flow
NIFI_API_VALIDATE_CERTS:
  type: boolean
  description: a flag, whether SSL certificates for NIFI_ENDPOINT should be validated. For self-signed certificates it should be false.
```
