### ISSUE TITLE
Support xOpera REST API version 2.0.0

### ISSUE THREAD

**Issue by mihaTrajbaric** [SODALITE-EU/ide#96]
xOpera REST API recently received [major API changes](https://github.com/SODALITE-EU/xopera-rest-api/pull/71), that need to be supported.

Here are new [api-spec.yml](https://github.com/SODALITE-EU/xopera-rest-api/blob/master/openapi-spec.yml), [detailed documentation](https://github.com/SODALITE-EU/xopera-rest-api#how-to-use-api) and [sample requests](https://github.com/SODALITE-EU/xopera-rest-api/blob/master/api-calls.http).

New xOpera REST API can be pulled from dockerhub

`docker pull sodaliteh2020/xopera-rest-api:2.0.0-beta`

and deployed with [docker-compose](https://drive.google.com/file/d/1fRLNoWWu5-oF2Ve_yLLiUspWN19Fqwyd/view).

# Major API changes

API received a lot of new functionality, here are just changes, that concern IDE - xOpera REST API integration

## Renamed parameters
- `blueprint_token` -> `blueprint_id`
- `version_tag` -> `version_id`
- `session_token` -> `deployment_id`

### Deploy (fresh)

```shell script
curl -X POST "[https or http]://[IP]:[PORT]/deployment/deploy?blueprint_id=[blueprint_id]&version_id=[version_id]&workers=[workers]" -H  "accept: application/json" -H  "X-API-Key: [API_key]" -H  "Content-Type: multipart/form-data" -F "inputs_file=@[inputs_file];type=application/x-yaml"
```
### Success
retun_json:
```python
{
  "blueprint_id": [blueprint_id],
  "deployment_id": [deployment_id],
  "inputs": [inputs],
  "operation": "deploy_fresh",
  "state": "pending",
  "timestamp": "2021-02-16T11:57:26.804961+00:00",
  "version_id": [version_id],
  "workers": [workers]
}
```
status_code: 202
### Unauthorized
```python
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```
status_code: 401
### Blueprint not found
```python
"Did not find blueprint with id: [blueprint_id] and version_id: [version_id]"
```
status_code: 404

## Status endpoint (info)

```shell script
curl -X GET "[https or http]://[IP]:[port]/deployment/[deployment_id]/status" -H  "accept: application/json" -H  "X-API-Key: [key]"
```

### Success
retun_json:
```python
{
  "blueprint_id": [blueprint_id],
  "version_id": [version_id],
  "deployment_id": [deployment_id],
  "state": [ pending, in_progress, success, failed ],
  "operation": "deploy_continue",
  "timestamp": "2021-02-16T12:09:30.920010+00:00",
  "inputs": [inputs],
  "instance_state": [instance_state],
  "outputs": [outputs],
  "exception": [exception_string],
  "stdout": [stdout_string],
  "stderr": [stderr_string],
  "workers": [workers]
}
```
status_code: 202
### Unauthorized
```python
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```
status_code: 401
### Deployment not found
```python
"Deployment with id: [deployment_id] does not exist"
```
status_code: 404

## Changed blueprint builder responses
Blueprint builder interacts with xOpera's /blueprint endpoint (former manage/) for saving blueprints, which now returns following json:

```python
# response example
{
  "blueprint_id": "beb9a0c4-64d8-4925-b634-fa928ce6472e",
  "commit_sha": "9ee3240643e77b8fe15532def843b7471eda5d5f",
  "timestamp": "2021-02-16T13:19:00.964968Z",
  "url": "https://gitlab.com/sodalite.xopera/gitDB_beb9a0c4-64d8-4925-b634-fa928ce6472e.git",
  "users": [
    "sodalite.xopera"
  ],
  "version_id": "v1.0"
}
```

**Comment by jesus-gorronogoitia** [comment]
Hi @mihaTrajbaric Could you please provide me real examples of returned json for both /deploy and /status APIs? Thanks

**Comment by mihaTrajbaric** [comment]
# Deploy endpoint:
request:
```bash script
curl -X POST "https://10.10.43.10:5001/deployment/deploy?blueprint_id=7c3f36d2-089c-403d-9723-a6275b5b69c1&version_id=v1.0&workers=10" -H  "accept: application/json" -H  "X-API-Key: test" -H  "Content-Type: multipart/form-data" -F "inputs_file=@hello_inputs.yaml;type=application/x-yaml"
```
response:
```yaml
{
  "blueprint_id": "7c3f36d2-089c-403d-9723-a6275b5b69c1",
  "deployment_id": "cfaf9b73-387d-429f-afa0-d1d9711e9ba9",
  "inputs": {
    "marker": "blah"
  },
  "operation": "deploy_fresh",
  "state": "pending",
  "timestamp": "2021-02-18T09:43:25.108404+00:00",
  "version_id": "v1.0",
  "workers": 10
}
```

# Status endpoint
request:
```bash script
curl -X GET "https://10.10.43.10:5001/deployment/cfaf9b73-387d-429f-afa0-d1d9711e9ba9/status" -H  "accept: application/json" -H  "X-API-Key: test"
```

response:
```yaml
{
  "blueprint_id": "7c3f36d2-089c-403d-9723-a6275b5b69c1",
  "deployment_id": "cfaf9b73-387d-429f-afa0-d1d9711e9ba9",
  "exception": "",
  "inputs": {
    "marker": "blah"
  },
  "instance_state": {
    "hello1": "started",
    "hello1-host-my-workstation": "initial",
    "hello2": "started",
    "hello2-host-my-workstation": "initial",
    "my-workstation": "started"
  },
  "operation": "deploy_fresh",
  "outputs": {
    "loc1": "{'description': '', 'value': '/tmp/playing-opera/hello1'}",
    "loc2": "{'description': '', 'value': '/tmp/playing-opera/hello2'}",
    "marker1": "{'description': '', 'value': 'foo'}",
    "marker2": "{'description': '', 'value': 'foo'}"
  },
  "state": "success",
  "stderr": "",
  "stdout": "\n                            \"size\": 3,\n                            \"state\": \"file\",\n                            \"uid\": 0\n                        }\n                    },\n                    \"task\": {\n                        \"duration\": {\n                            \"end\": \"2021-02-18T09:46:34.624930Z\",\n                            \"start\": \"2021-02-18T09:46:33.602858Z\"\n                        },\n                        \"id\": \"0242ac11-0003-4634-fa08-000000000009\",\n                        \"name\": \"Ansible was here\"\n                    }\n                }\n            ]\n        }\n    ],\n    \"stats\": {\n        \"opera\": {\n            \"changed\": 0,\n            \"failures\": 0,\n            \"ignored\": 0,\n            \"ok\": 2,\n            \"rescued\": 0,\n            \"skipped\": 0,\n            \"unreachable\": 0\n        }\n    }\n}\n[Worker_0] ------------\n[Worker_0] ============\n[Worker_0]   Deployment of hello1_0 complete\n[Worker_0]   Deploying my-workstation_0\n[Worker_0]   Deployment of my-workstation_0 complete\n[Worker_0]   Deploying hello1_0\n[Worker_0]     Executing create on hello1_0\n***inputs***\n['marker: foo', 'location: /tmp/playing-opera/hello1']\n***inputs***\n[Worker_1]   Deploying hello2_0\n[Worker_1]     Executing create on hello2_0\n***inputs***\n['marker: foo', 'location: /tmp/playing-opera/hello2']\n***inputs***\n[Worker_1] ------------\n{\n    \"custom_stats\": {},\n    \"global_custom_stats\": {},\n    \"plays\": [\n        {\n            \"play\": {\n                \"duration\": {\n                    \"end\": \"2021-02-18T09:48:22.987318Z\",\n                    \"start\": \"2021-02-18T09:48:21.241797Z\"\n                },\n                \"id\": \"0242ac11-0003-6830-98bb-000000000006\",\n                \"name\": \"all\"\n            },\n            \"tasks\": [\n                {\n                    \"hosts\": {\n                        \"opera\": {\n                            \"_ansible_no_log\": false,\n                            \"action\": \"file\",\n                            \"changed\": false,\n                            \"diff\": {\n                                \"after\": {\n                                    \"path\": \"/tmp/playing-opera/hello2\"\n                                },\n                                \"before\": {\n                                    \"path\": \"/tmp/playing-opera/hello2\"\n                                }\n                            },\n                            \"gid\": 0,\n                            \"group\": \"root\",\n                            \"invocation\": {\n                                \"module_args\": {\n                                    \"_diff_peek\": null,\n                                    \"_original_basename\": null,\n                                    \"access_time\": null,\n                                    \"access_time_format\": \"%Y%m%d%H%M.%S\",\n                                    \"attributes\": null,\n                                    \"follow\": true,\n                                    \"force\": false,\n                                    \"group\": null,\n                                    \"mode\": null,\n                                    \"modification_time\": null,\n                                    \"modification_time_format\": \"%Y%m%d%H%M.%S\",\n                                    \"owner\": null,\n                                    \"path\": \"/tmp/playing-opera/hello2\",\n                                    \"recurse\": true,\n                                    \"selevel\": null,\n                                    \"serole\": null,\n                                    \"setype\": null,\n                                    \"seuser\": null,\n                                    \"src\": null,\n                                    \"state\": \"directory\",\n                                    \"unsafe_writes\": false\n                                }\n                            },\n                            \"mode\": \"0755\",\n                            \"owner\": \"root\",\n                            \"path\": \"/tmp/playing-opera/hello2\",\n                            \"size\": 4096,\n                            \"state\": \"directory\",\n                            \"uid\": 0\n                        }\n                    },\n                    \"task\": {\n                        \"duration\": {\n                            \"end\": \"2021-02-18T09:48:21.915297Z\",\n                            \"start\": \"2021-02-18T09:48:21.258737Z\"\n                        },\n                        \"id\": \"0242ac11-0003-6830-98bb-000000000008\",\n                        \"name\": \"Make the location\"\n                    }\n                },\n                {\n                    \"hosts\": {\n                        \"opera\": {\n                            \"_ansible_no_log\": false,\n                            \"action\": \"copy\",\n                            \"changed\": false,\n                            \"checksum\": \"0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33\",\n                            \"dest\": \"/tmp/playing-opera/hello2/hello.txt\",\n                            \"diff\": {\n                                \"after\": {\n                                    \"path\": \"/tmp/playing-opera/hello2/hello.txt\"\n                                },\n                                \"before\": {\n                                    \"path\": \"/tmp/playing-opera/hello2/hello.txt\"\n                                }\n                            },\n                            \"gid\": 0,\n                            \"group\": \"root\",\n                            \"invocation\": {\n                                \"module_args\": {\n                                    \"_diff_peek\": null,\n                                    \"_original_basename\": \"tmpkiurrosc\",\n                                    \"access_time\": null,\n                                    \"access_time_format\": \"%Y%m%d%H%M.%S\",\n                                    \"attributes\": null,\n                                    \"dest\": \"/tmp/playing-opera/hello2/hello.txt\",\n                                    \"follow\": true,\n                                    \"force\": false,\n                                    \"group\": null,\n                                    \"mode\": null,\n                                    \"modification_time\": null,\n                                    \"modification_time_format\": \"%Y%m%d%H%M.%S\",\n                                    \"owner\": null,\n                                    \"path\": \"/tmp/playing-opera/hello2/hello.txt\",\n                                    \"recurse\": false,\n                                    \"selevel\": null,\n                                    \"serole\": null,\n                                    \"setype\": null,\n                                    \"seuser\": null,\n                                    \"src\": null,\n                                    \"state\": \"file\",\n                                    \"unsafe_writes\": false\n                                }\n                            },\n                            \"mode\": \"0644\",\n                            \"owner\": \"root\",\n                            \"path\": \"/tmp/playing-opera/hello2/hello.txt\",\n                            \"size\": 3,\n                            \"state\": \"file\",\n                            \"uid\": 0\n                        }\n                    },\n                    \"task\": {\n                        \"duration\": {\n                            \"end\": \"2021-02-18T09:48:22.987318Z\",\n                            \"start\": \"2021-02-18T09:48:21.920474Z\"\n                        },\n                        \"id\": \"0242ac11-0003-6830-98bb-000000000009\",\n                        \"name\": \"Ansible was here\"\n                    }\n                }\n            ]\n        }\n    ],\n    \"stats\": {\n        \"opera\": {\n            \"changed\": 0,\n            \"failures\": 0,\n            \"ignored\": 0,\n            \"ok\": 2,\n            \"rescued\": 0,\n            \"skipped\": 0,\n            \"unreachable\": 0\n        }\n    }\n}\n[Worker_1] ------------\n[Worker_1] ============\n[Worker_1]   Deployment of hello2_0 complete\n[Worker_0] ------------\n{\n    \"custom_stats\": {},\n    \"global_custom_stats\": {},\n    \"plays\": [\n        {\n            \"play\": {\n                \"duration\": {\n                    \"end\": \"2021-02-18T09:48:23.150809Z\",\n                    \"start\": \"2021-02-18T09:48:21.246362Z\"",
  "timestamp": "2021-02-18T09:48:14.082473+00:00",
  "version_id": "v1.0",
  "workers": 10
}
```
