### ISSUE TITLE
RM TTL generated by IDE is missing keywords in Interface definition

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/ide#97]
## Current behaviour
When IDE generates a TTL file for a Resource Model it omits `operations`, `default` and `inputs` keywords
E.g. for an RM like this
```
module: openstack
node_types:
	sodalite.nodes.Compute:
		derived_from: tosca.nodes.Compute
		properties: 
			username:
				type: string
			docker_ip:
				type: string
			
		interfaces:		
			Standard:
				type: tosca.interfaces.node.lifecycle.Standard				
				operations:          
					create: 
						inputs:
							docker_ip:
								default: get_property: 
									entity: SELF
									property: sodalite.nodes.Compute.docker_ip
						implementation:						
							primary:  "playbooks/set_ip.yaml"
```
TTL would be
```
# baseURI: https://www.sodalite.eu/ontologies/exchange/rm/
# imports: https://www.sodalite.eu/ontologies/exchange/

@prefix : <https://www.sodalite.eu/ontologies/exchange/rm/> .
@prefix exchange: <https://www.sodalite.eu/ontologies/exchange/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:
  rdf:type owl:Ontology ;
  owl:imports exchange: ;
  owl:versionInfo "Created by the SODALITE IDE" ;
.

:RM_1
  rdf:type exchange:RM ;
  exchange:userId "27827d44-0f6c-11ea-8d71-362b9e155667" ;
.


:Parameter_1
  rdf:type exchange:Parameter ;
  exchange:name "property" ;  
  exchange:value 'docker_ip' ; 
.

:Parameter_2
  rdf:type exchange:Parameter ;
  exchange:name "entity" ;  
  exchange:value 'SELF' ; 
.


:Parameter_3
  rdf:type exchange:Parameter ;
  exchange:name "get_property" ;
  exchange:hasParameter :Parameter_1 ;
  exchange:hasParameter :Parameter_2 ;
.	





:Parameter_4
  rdf:type exchange:Parameter ;
  exchange:name "value" ;
  exchange:hasParameter :Parameter_3 ;
.

:Parameter_5
  rdf:type exchange:Parameter ;
  exchange:name "docker_ip" ;
  exchange:hasParameter :Parameter_4 ;
.	


:Parameter_6
  rdf:type exchange:Parameter ;
  exchange:name "path" ;
  exchange:value 'playbooks/set_ip.yaml' ;
.

:Parameter_7
  rdf:type exchange:Parameter ;
  exchange:name "content" ;
  exchange:value '- hosts: all\n  gather_facts: no\n  tasks:\n    - name: Set attributes\n      set_stats:\n        data:\n          private_address: "{{ docker_ip }}"\n          public_address: "{{ docker_ip }}"' ;
.


:Parameter_8
  rdf:type exchange:Parameter ;
  exchange:name "primary" ;
  exchange:hasParameter :Parameter_6 ;
  exchange:hasParameter :Parameter_7 ;
.


:Parameter_9
  rdf:type exchange:Parameter ;
  exchange:name "implementation" ;
  exchange:hasParameter :Parameter_8 ;
.

:Parameter_10
  rdf:type exchange:Parameter ;
  exchange:name "create" ;
  exchange:hasParameter :Parameter_5 ;
  exchange:hasParameter :Parameter_9 ;
.

:Parameter_11
  rdf:type exchange:Parameter ;
  exchange:name "type" ;
  exchange:value 'string' ;  
.

:Parameter_12
  rdf:type exchange:Parameter ;
  exchange:name "required" ;
  exchange:value 'false' ;
.

:Property_1
  rdf:type exchange:Property ;
  exchange:name "username" ;
  exchange:hasParameter :Parameter_11 ;
  exchange:hasParameter :Parameter_12 ;
.
:Parameter_13
  rdf:type exchange:Parameter ;
  exchange:name "type" ;
  exchange:value 'string' ;  
.

:Parameter_14
  rdf:type exchange:Parameter ;
  exchange:name "required" ;
  exchange:value 'false' ;
.

:Property_2
  rdf:type exchange:Property ;
  exchange:name "docker_ip" ;
  exchange:hasParameter :Parameter_13 ;
  exchange:hasParameter :Parameter_14 ;
.

:Parameter_15
  rdf:type exchange:Parameter ;
  exchange:name "type" ;
  exchange:value 'tosca.interfaces.node.lifecycle.Standard' ;
.

:Interface_1
  rdf:type exchange:Interface ;
  exchange:name "Standard" ;
  exchange:hasParameter :Parameter_15 ;
  exchange:hasParameter :Parameter_10 ;
.

:NodeType_1
  rdf:type exchange:Type ;
  exchange:name "sodalite.nodes.Compute" ;
  exchange:derivesFrom 'tosca.nodes.Compute' ;  
  exchange:properties :Property_1 ; 
  exchange:properties :Property_2 ; 
  exchange:interfaces :Interface_1 ; 
.  
```
and eventually generated TOSCA would have interface definition like this
```
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        create:
          implementation:
            primary: playbooks/8a50b2ad-9960-4b90-ad6a-a60bab69976f_set_ip.yaml
          docker_ip:
            get_property:
            - SELF
            - docker_ip
```

## Expected behaviour
TTL should be generated in a way so the resulting TOSCA would be
```
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            implementation:
              primary: playbooks/8a50b2ad-9960-4b90-ad6a-a60bab69976f_set_ip.yaml
            inputs:  
              docker_ip:
                type: string
                default:
                  get_property:
                  - SELF
                  - docker_ip
```
